# Generated by Django 5.2.7 on 2025-10-24 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('accion', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('nivel', models.CharField(choices=[('info', 'Info'), ('advertencia', 'Advertencia'), ('error', 'Error')], default='info', max_length=20)),
                ('detalles', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcesoMonitoreado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('error', 'Error'), ('en_ejecucion', 'En ejecución')], default='activo', max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
